Repository sainiharit/PICTOSA, pull requests merged in 2022-10, with the labels that each got.

#1 Create activity_main.xml
  java-assets/activity_main.xml
Labels: hacktoberfest-accepted

#4 Create ViewAnimator
  java-assets/ViewAnimator
Labels: enhancement, help wanted, hacktoberfest-accepted

#3 Create MainActivity(Kotlin)
  java-assets/MainActivity(Kotlin)
Labels: enhancement, good first issue, hacktoberfest-accepted

#12 Create AndroidManifest.xml
  java-assets/AndroidManifest.xml
Labels: enhancement, hacktoberfest-accepted

#11 Create login-main.xml
  java-assets/login-main.xml
Labels: enhancement, hacktoberfest-accepted

#10 Update and rename MainActivity to MainActivity.java
  java-assets/MainActivity.java
Labels: enhancement, hacktoberfest-accepted

#5 Update ViewAnimator
  java-assets/ViewAnimator
Labels: enhancement, hacktoberfest-accepted

#6 Create push-notification.java
  java-assets/push-notification.java
Labels: enhancement, hacktoberfest-accepted

#7 Create push-notification.xml
  java-assets/push-notification.xml
Labels: enhancement, hacktoberfest-accepted

#8 Create layout.xml
  java-assets/layout.xml
Labels: enhancement, hacktoberfest-accepted

#9 Update MainActivity
  java-assets/MainActivity
Labels: enhancement, hacktoberfest-accepted

#13 Create mainactivity.java
  mainpage/mainactivity.java
Labels: hacktoberfest-accepted

#16 Create mainpage.xml
  mainpage/mainpage.xml
Labels: enhancement, hacktoberfest-accepted

#15 Update push-notification.java
  java-assets/push-notification.java
Labels: enhancement, hacktoberfest-accepted

#14 Update MainActivity
  java-assets/MainActivity
Labels: enhancement, hacktoberfest-accepted
